### PR TITLE
Dryville_story.md edit Issue #1

### PR DESCRIPTION
**Pull request by corrinecelupica**
Added into 2 additional sections to Dryville story, "Getting Water to your Homes" and "Dryville's First Water Works".

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Switching reviewers to @abnerbog who is your course contact! We can still help you move through this training, but it may be at a slower pace than last week would have permitted. Thanks and hope the Summer Institute is off to a great start this week!

**Comment by abnerbog** [comment]
[like]  Abner Bogan reacted to your message:
________________________________

**Review by abnerbog — APPROVED** [review]
Corrine -- this is perfect ! You're all set to move on to the next step :)

**Comment by corrinecelupica** [comment]
@abnerbog Thanks for your comment :) On the next step, it says that a collaborator is supposed to add the next section of the story. Would you be able to help me with this? Apologies if you did do it and I just missed it. Thanks!

**Pull request merged**
